In [149]:
import numpy as np 
import pandas as pd
import os

In [150]:
nw1 = pd.read_csv("R_Module_Day_12.1_Network_Intrusion_Train_data.csv")

In [151]:
nw2 = pd.read_csv("R_Module_Day_12.3_Network_Intrusion_Validate_data.csv")

In [152]:
nw1.head()

duration protocol_type   service flag  src_bytes  dst_bytes  land  \
0         0           tcp  ftp_data   SF        491          0     0   
1         0           udp     other   SF        146          0     0   
2         0           tcp   private   S0          0          0     0   
3         0           tcp      http   SF        232       8153     0   
4         0           tcp      http   SF        199        420     0   

   wrong_fragment  urgent  hot   ...     dst_host_srv_count  \
0               0       0    0   ...                     25   
1               0       0    0   ...                      1   
2               0       0    0   ...                     26   
3               0       0    0   ...                    255   
4               0       0    0   ...                    255   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                    0.17                    0.03   
1                    0.00                    0.60   
2                    0.10                    0.05   
3                    1.00                    0.00   
4                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                         0.00   
1                         0.88                         0.00   
2                         0.00                         0.00   
3                         0.03                         0.04   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                  0.05   
1                  0.00                      0.00                  0.00   
2                  1.00                      1.00                  0.00   
3                  0.03                      0.01                  0.00   
4                  0.00                      0.00                  0.00   

   dst_host_srv_rerror_rate    class  
0                      0.00   normal  
1                      0.00   normal  
2                      0.00  anomaly  
3                      0.01   normal  
4                      0.00   normal  

[5 rows x 42 columns]

In [153]:
nw2.dtypes

duration                         int64
protocol_type                   object
service                         object
flag                            object
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate          

In [154]:
nw2.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_h

In [155]:
# Do imputations

nw1['protocol_type'] = nw1['protocol_type'].astype('category')
nw1['protocol_type'] = nw1['protocol_type'].cat.codes
nw1['service'] = nw1['service'].astype('category')
nw1['service'] = nw1['service'].cat.codes
nw1['flag'] = nw1['flag'].astype('category')
nw1['flag'] = nw1['flag'].cat.codes

In [156]:
nw2['protocol_type'] = nw2['protocol_type'].astype('category')
nw2['protocol_type'] = nw2['protocol_type'].cat.codes
nw2['service'] = nw2['service'].astype('category')
nw2['service'] = nw2['service'].cat.codes
nw2['flag'] = nw2['flag'].astype('category')
nw2['flag'] = nw2['flag'].cat.codes

In [157]:
nw1.dtypes

duration                         int64
protocol_type                     int8
service                           int8
flag                              int8
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
hot                              int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_root                         int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
count                            int64
srv_count                        int64
serror_rate                    float64
srv_serror_rate          

In [158]:
len(nw1.columns)

42

In [159]:
# Split into i/p and 0/p

train_x = nw1.iloc[:,0:41]
train_y = nw1.iloc[:,41:]

In [160]:
train_y.head()

class
0   normal
1   normal
2  anomaly
3   normal
4   normal

In [161]:
val_x = nw2.iloc[:,0:41]
val_y = nw2.iloc[:,41:]

In [162]:
train_x.head()

duration  protocol_type  service  flag  src_bytes  dst_bytes  land  \
0         0              1       19     9        491          0     0   
1         0              2       41     9        146          0     0   
2         0              1       46     5          0          0     0   
3         0              1       22     9        232       8153     0   
4         0              1       22     9        199        420     0   

   wrong_fragment  urgent  hot            ...             dst_host_count  \
0               0       0    0            ...                        150   
1               0       0    0            ...                        255   
2               0       0    0            ...                        255   
3               0       0    0            ...                         30   
4               0       0    0            ...                        255   

   dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                  25                    0.17                    0.03   
1                   1                    0.00                    0.60   
2                  26                    0.10                    0.05   
3                 255                    1.00                    0.00   
4                 255                    1.00                    0.00   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.17                         0.00   
1                         0.88                         0.00   
2                         0.00                         0.00   
3                         0.03                         0.04   
4                         0.00                         0.00   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                  0.00                      0.00                  0.05   
1                  0.00                      0.00                  0.00   
2                  1.00                      1.00                  0.00   
3                  0.03                      0.01                  0.00   
4                  0.00                      0.00                  0.00   

   dst_host_srv_rerror_rate  
0                      0.00  
1                      0.00  
2                      0.00  
3                      0.01  
4                      0.00  

[5 rows x 41 columns]

In [169]:
val_x.groupby('flag').agg({'flag':np.size})

flag
flag       
0         4
1      3850
2       773
3         2
4       669
5      2013
6        21
7        15
8       249
9     14875
10       73

In [170]:
# Make dummies  in train dataset

train_x = pd.get_dummies(train_x,columns = ['protocol_type'],drop_first = True)

In [171]:
train_x.head()

duration  service  flag  src_bytes  dst_bytes  land  wrong_fragment  \
0         0       19     9        491          0     0               0   
1         0       41     9        146          0     0               0   
2         0       46     5          0          0     0               0   
3         0       22     9        232       8153     0               0   
4         0       22     9        199        420     0               0   

   urgent  hot  num_failed_logins       ...         dst_host_same_srv_rate  \
0       0    0                  0       ...                           0.17   
1       0    0                  0       ...                           0.00   
2       0    0                  0       ...                           0.10   
3       0    0                  0       ...                           1.00   
4       0    0                  0       ...                           1.00   

   dst_host_diff_srv_rate  dst_host_same_src_port_rate  \
0                    0.03                         0.17   
1                    0.60                         0.88   
2                    0.05                         0.00   
3                    0.00                         0.03   
4                    0.00                         0.00   

   dst_host_srv_diff_host_rate  dst_host_serror_rate  \
0                         0.00                  0.00   
1                         0.00                  0.00   
2                         0.00                  1.00   
3                         0.04                  0.03   
4                         0.00                  0.00   

   dst_host_srv_serror_rate  dst_host_rerror_rate  dst_host_srv_rerror_rate  \
0                      0.00                  0.05                      0.00   
1                      0.00                  0.00                      0.00   
2                      1.00                  0.00                      0.00   
3                      0.01                  0.00                      0.01   
4                      0.00                  0.00                      0.00   

   protocol_type_1  protocol_type_2  
0                1                0  
1                0                1  
2                1                0  
3                1                0  
4                1                0  

[5 rows x 42 columns]

In [172]:
train_x = pd.get_dummies(train_x,columns = ['flag'],drop_first = True)

In [173]:
train_x.head()

duration  service  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0         0       19        491          0     0               0       0    0   
1         0       41        146          0     0               0       0    0   
2         0       46          0          0     0               0       0    0   
3         0       22        232       8153     0               0       0    0   
4         0       22        199        420     0               0       0    0   

   num_failed_logins  logged_in   ...     flag_1  flag_2  flag_3  flag_4  \
0                  0          0   ...          0       0       0       0   
1                  0          0   ...          0       0       0       0   
2                  0          0   ...          0       0       0       0   
3                  0          1   ...          0       0       0       0   
4                  0          1   ...          0       0       0       0   

   flag_5  flag_6  flag_7  flag_8  flag_9  flag_10  
0       0       0       0       0       1        0  
1       0       0       0       0       1        0  
2       1       0       0       0       0        0  
3       0       0       0       0       1        0  
4       0       0       0       0       1        0  

[5 rows x 51 columns]

In [175]:
# Make tarin dataset into array

x_train_x = train_x.iloc[:,:].values

In [176]:
# Make dummies in test dataset

val_x = pd.get_dummies(val_x,columns = ['protocol_type'],drop_first = True)

In [177]:
val_x = pd.get_dummies(val_x,columns = ['flag'],drop_first = True)

In [178]:
val_x.head()

duration  service  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0         0       45          0          0     0               0       0    0   
1         0       45          0          0     0               0       0    0   
2         2       19      12983          0     0               0       0    0   
3         0       13         20          0     0               0       0    0   
4         1       55          0         15     0               0       0    0   

   num_failed_logins  logged_in   ...     flag_1  flag_2  flag_3  flag_4  \
0                  0          0   ...          1       0       0       0   
1                  0          0   ...          1       0       0       0   
2                  0          0   ...          0       0       0       0   
3                  0          0   ...          0       0       0       0   
4                  0          0   ...          0       1       0       0   

   flag_5  flag_6  flag_7  flag_8  flag_9  flag_10  
0       0       0       0       0       0        0  
1       0       0       0       0       0        0  
2       0       0       0       0       1        0  
3       0       0       0       0       1        0  
4       0       0       0       0       0        0  

[5 rows x 51 columns]

In [179]:
x_val_x = val_x.iloc[:,:].values

In [180]:
x_val_x

array([[0.0000e+00, 4.5000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [0.0000e+00, 4.5000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.0000e+00, 1.9000e+01, 1.2983e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       ...,
       [0.0000e+00, 2.2000e+01, 5.4540e+04, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [0.0000e+00, 1.1000e+01, 4.2000e+01, ..., 0.0000e+00, 1.0000e+00,
        0.0000e+00],
       [0.0000e+00, 5.2000e+01, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [181]:
train_y['class'] = train_y['class'].astype('category')
train_y['class'] = train_y['class'].cat.codes

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [182]:
val_y['class'] = val_y['class'].astype('category')
val_y['class'] = val_y['class'].cat.codes

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [183]:
train_y.head()

class
0      1
1      1
2      0
3      1
4      1

In [184]:
y_train_y = train_y.iloc[:,:].values

In [185]:
y_val_y = val_y.iloc[:,:].values

In [186]:
y_train_y

array([[1],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int8)

In [190]:
# Now do scaling

from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
x_train_x= stdsc.fit_transform(x_train_x)
x_val_x = stdsc.transform(x_val_x)

In [191]:
# Making decision tree model

from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(criterion = 'entropy',random_state = 0)
dtc.fit(x_train_x,y_train_y)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [192]:
# Do prediction 

y_pred_DT = dtc.predict (x_val_x)

In [193]:
# find confusion matrix and accurecy of the model

from sklearn.metrics import confusion_matrix,accuracy_score
cm_DT = confusion_matrix(y_pred_DT,y_val_y)
acc_DT = accuracy_score(y_pred_DT,y_val_y)
print("confusion matrix is\n %s"%cm_DT)
print("accuracy of decision tree model is %s"%acc_DT)

confusion matrix is
 [[9051  302]
 [3782 9409]]
accuracy of decision tree model is 0.8188431511710433


In [195]:
# Make random forest model

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 50,random_state = 0, criterion = 'entropy')
rfc.fit(x_train_x,y_train_y)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [196]:
y_pred_rfc = rfc.predict(x_val_x)

In [202]:
cm_rfc =confusion_matrix(y_val_y,y_pred_rfc)
acc_rfc = accuracy_score(y_val_y,y_pred_rfc)
print("confusion matrix is\n %s"%cm_rfc)
print("accuracy of decision tree model is %s"%acc_rfc)

confusion matrix is
 [[8322 4511]
 [ 256 9455]]
accuracy of decision tree model is 0.7885468417317246
